version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TOKEN_GIRL_BOT=${TOKEN_GIRL_BOT}
    volumes:
      - "/codebase:/codebase"
      - "/storage:/storage"
    restart: always